name: "nbsphinx publisher"
# via: https://github.com/s-weigand/nbsphinx/blob/gh-action-ci-switch/.github/workflows/test.yml
on:
  push:
    branches:
      - master
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm install
        npm install --global gatsby-cli

    - name: Use build branch context
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git checkout -b build
        git merge master
    - name: Build docs HTML
      run: |
        if [ ! -f .path_config_set ]; then
          echo "module.exports = { pathPrefix: \"/${GITHUB_REPOSITORY##*/}\"}" >> gatsby-config.js
          touch .path_config_set
        fi
        
        gatsby build --prefix-paths
        git push

    - name: Deploy HTML site to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
